#!/bin/bash      

#set -eux
#set -o pipefail

#msqlBase=${msqlBase:-"testBase"}
#msqlUsr=${msqlUsr:-"testUser"}
#msqlUsrPass=${msqlUsrPass:-"testPass"}

#MYSQL=`which mysql`

#Q1="CREATE DATABASE IF NOT EXISTS $msqlBase;"
#Q2="GRANT USAGE ON *.* TO $msqlUsr@127.0.0.1 IDENTIFIED BY '$msqlUsrPass';"
#Q3="GRANT ALL PRIVILEGES ON $msqlBase.* TO $msqlUsr@127.0.0.1;"
#Q4="FLUSH PRIVILEGES;"
#SQL="${Q1}${Q2}${Q3}${Q4}"

#systemctl start mysqld.service
#/etc/init.d/mysql start
#chown -R mysql.mysql /var/lib/mysql

#$MYSQL -uroot -e "$SQL"

