#!/bin/bash

set -eux
set -o pipefail

export DEBIAN_FRONTEND=noninteractive
export mngHome=${mngHome:-"/opt/mongodb"}

mngVer=${mngVer:-"2.6.4"}
mngRep=${mngRep:-false}
mngDB=${mngDB:-"/data/db"}

if [[ $mngRep == true ]]
   then
      if [[ $DISTRO_NAME == "ubuntu" ]]
         then
            apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
            echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list
            apt-get update
            install-packages mongodb-org
            
            update-rc.d mongod disable
         else
            echo "[mongodb]
name=MongoDB Repository
baseurl=http://downloads-distro.mongodb.org/repo/redhat/os/x86_64/
gpgcheck=0
enabled=1" > /etc/yum.repos.d/mongodb.repo
            install-packages mongodb-org

            chkconfig mongod off
      fi
   else
      useradd -m -d ${mngHome} -s /bin/bash -c "User for mongodb" -p mongodb -U mongodb
      chown -R mongodb:mongodb ${mngHome}

      su - mongodb -c 'echo "export PATH=${PATH}:"${mngHome}/bin"" >> ~/.bashrc'
      echo "export PATH=${PATH}:"${mngHome}/bin"" >> ~/.bashrc
      su - mongodb -c 'export PATH=${PATH}:"${mngHome}/bin"'
      export PATH=${PATH}:"${mngHome}/bin"

      if [[ $ARCH == "amd64" ]]
         then
            larch="x86_64"
         else
            larch="i686"
      fi

      pushd ${mngHome}

      curl -LO "http://downloads.mongodb.org/linux/mongodb-linux-${larch}-${mngVer}.tgz"
      tar -zxvf mongodb-linux-${larch}-${mngVer}.tgz
      rm -f mongodb-linux-${larch}-${mngVer}.tgz 
      mv mongodb-linux-${larch}-${mngVer}/* ../mongodb

      popd

      mkdir -p ${mngDB}
      chown -R mongodb:mongodb ${mngDB}
fi
