#!/bin/bash

set -eux
set -o pipefail

export DEBIAN_FRONTEND=noninteractive
export mngHome=${mngHome:-"/opt/mongodb"}

mngVer=${mngVer:-"2.6.4"}
mngRep=${mngRep:-false}
mngDB=${mngDB:-"/data/db"}

if [[ $mngRep == true ]]
   then
      if [[ $DISTRO_NAME == "ubuntu" ]]
         then
            apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
            echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list
            apt-get update
            install-packages mongodb-org
         else
            echo "[mongodb]
name=MongoDB Repository
baseurl=http://downloads-distro.mongodb.org/repo/redhat/os/x86_64/
gpgcheck=0
enabled=1" > /etc/yum.repos.d/mongodb.repo
            install-packages $(map-packages mongodb-org)
      fi
   else
      useradd -m -d ${mngHome} -s /bin/bash -c "User for mongodb" -p mongodb -U mongodb
      chown -R mongodb:mongodb ${mngHome}

      su - mongodb -c 'echo "export PATH=${PATH}:"${mngHome}/bin"" >> ~/.bashrc'
      su -c 'echo "export PATH=${PATH}:"${mngHome}/bin"" >> ~/.bashrc'
      su - mongodb -c 'export PATH=${PATH}:"${mngHome}/bin"'
      su -c 'export PATH=${PATH}:"${mngHome}/bin"'

      if [[ $ARCH == "amd64" ]]
         then
            larch="x86_64"
         else
            larch="i686"
      fi

      cd ${mngHome}
      if [[ $DISTRO_NAME == "ubuntu" ]]
         then
            wget "http://downloads.mongodb.org/linux/mongodb-linux-${larch}-${mngVer}.tgz"
         else
            curl -O "http://downloads.mongodb.org/linux/mongodb-linux-${larch}-${mngVer}.tgz"
      fi
      tar -zxvf mongodb-linux-${larch}-${mngVer}.tgz 
      mv mongodb-linux-${larch}-${mngVer}/* ../mongodb 

      mkdir -p ${mngDB}
      chown -R mongodb:mongodb ${mngDB}
fi
