#!/bin/bash

set -eux
set -o pipefail

export DEBIAN_FRONTEND=noninteractive
export msqlHome=${msqlHome:-"/opt/mysql"}

msqlRep=${msqlRep:-false}
msqlVer=${msqlVer:-"5.6.22"}
mariaVer=${mariaVer:-"5.5.40"}

install-packages udev

if [[ $msqlRep == true ]]
   then
      if [[ $DISTRO_NAME != "ubuntu" ]]
         then
            echo "# MariaDB 10.0 CentOS repository list - created 2014-12-08 10:16 UTC
# http://mariadb.org/mariadb/repositories/
[mariadb]
name = MariaDB
baseurl = http://yum.mariadb.org/10.0/centos7-amd64
gpgkey=https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
gpgcheck=1" > /etc/yum.repos.d/MariaDB.repo
      fi
      install-packages mysql-server mysql-client 
   else
      mkdir -p /tmp/mysql
      pushd /tmp/mysql
      if [[ $DISTRO_NAME == "ubuntu" ]]
         then
            curl -LO "dev.mysql.com/get/Downloads/MySQL-${msqlVer%%.}/mysql-server_${msqlVer}-2ubuntu14.04_${ARCH}.deb-bundle.tar"
            tar -xvf mysql-server_${msqlVer}-2ubuntu14.04_${ARCH}.deb-bundle.tar

            install-packages libaio1 dpkg-dev
            dpkg-scanpackages . /dev/null | gzip -9c > Packages.gz
            mv /etc/apt/sources.list /etc/apt/sources.list.tmp
            echo "deb file:/tmp/mysql ./" > /etc/apt/sources.list

            apt-get update
            apt-get -y --force-yes  install mysql-server mysql-client
            mv -f /etc/apt/sources.list.tmp /etc/apt/sources.list
            apt-get update
         else
            yum -y remove mariadb-libs-1:5.5.37-1.el7_0.x86_64

            install-packages wget createrepo
            wget -m -p -E -k -K -np -nd http://mirror.timeweb.ru/mariadb/mariadb-${mariaVer}/yum/centos7-${ARCH}/rpms/

            createrepo .
            echo "[local]
name=CentOS - local packages
baseurl=file:///tmp/mysql
enabled=1
gpgcheck=0
protect=1
priority=1" > /etc/yum.repos.d/local.repo
            
            yum -y install MariaDB-server MariaDB-client
      fi
      popd
      rm -rf  /tmp/mysql
fi
