#!/bin/bash

set -eux
set -o pipefail

msqlBase=${msqlBase:-"testBase"}
msqlUsr=${msqlUsr:-"testUser"}
msqlUsrPass=${msqlUsrPass:-"testPass"}

mv /etc/rc.local /etc/rc.local.tmp

echo "#!/bin/bash

# rc.local

sudo /etc/init.d/mysql start

MYSQL="'`which mysql`'"

Q1=\"CREATE DATABASE IF NOT EXISTS $msqlBase;\"
Q2=\"GRANT USAGE ON *.* TO $msqlUsr@localhost IDENTIFIED BY "'\"'"$msqlUsrPass"'\"'";\"
Q3=\"GRANT ALL PRIVILEGES ON $msqlBase.* TO $msqlUsr@localhost;\"
Q4=\"FLUSH PRIVILEGES;\"
SQL=\""'${Q1}${Q2}${Q3}${Q4}'"\"

"'$MYSQL'" -uroot -e "'"$SQL"'"

sudo mv -f /etc/rc.local.tmp /etc/rc.local" > /etc/rc.local

chmod 755 /etc/rc.local
